import Head from "next/head"
import Header from "../../components/Header"
import Form from "../../components/Form"
import PostFeed from "../../components/posts/PostFeed"

export default function Home() {
  return (
    <>
      <Head>
        <title>Buzzworthy</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
     <Header label="Home" />
     <Form placeholder="What's happening?" />
     <PostFeed />
    </>
  )
}
